=== KDE/binschema/src/mso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/mso"
	xmlns:tns="http://www.example.org/mso" elementFormDefault="qualified">
	<complexType name="limitationType">
		<attribute name="name" type="NCName" use="optional" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="valueRef" type="string" use="optional" />
		<attribute name="expression" type="string" use="optional" />
	</complexType>
	<complexType name="msoMemberType" abstract="true">
		<choice maxOccurs="unbounded" minOccurs="0">
			<element name="limitation" type="tns:limitationType" />
		</choice>
		<attribute name="name" type="NCName" use="required" />
		<attribute name="array" type="boolean" use="optional"
			default="false" />
		<attribute name="count" type="string" use="optional" />
		<attribute name="minOccurs" type="string" use="optional" />
		<attribute name="maxOccurs" type="string" use="optional" />
		<attribute name="condition" type="string" use="optional" />
	</complexType>
	<complexType name="intType">
		<complexContent>
			<extension base="tns:msoMemberType">
				<attribute name="default" type="int" use="optional" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="typeType">
		<complexContent>
			<extension base="tns:msoMemberType">
				<attribute name="type" type="NCName" use="required" />
				<attribute name="optional" type="boolean" use="optional"
					default="false" />
				<!-- if the size is know it can be specified here as an expression -->
				<attribute name="size" type="string" use="optional" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="choiceType">
		<choice>
			<element name="type" minOccurs="2" maxOccurs="unbounded">
				<complexType>
					<attribute name="type" type="NCName" use="required" />
				</complexType>
			</element>
			<choice minOccurs="2" maxOccurs="unbounded">
				<element name="text" type="string" />
				<element name="hex" type="hexBinary" />
			</choice>
		</choice>
		<attribute name="name" type="NCName" use="required" />
		<attribute name="optional" type="boolean" use="optional"
			default="false" />
	</complexType>
	<complexType name="structType">
		<sequence>
			<choice maxOccurs="unbounded" minOccurs="0">
				<element name="bit" type="tns:intType" />
				<element name="int16" type="tns:intType" />
				<element name="int32" type="tns:intType" />
				<element name="uint2" type="tns:intType" />
				<element name="uint3" type="tns:intType" />
				<element name="uint4" type="tns:intType" />
				<element name="uint5" type="tns:intType" />
				<element name="uint6" type="tns:intType" />
				<element name="uint7" type="tns:intType" />
				<element name="uint8" type="tns:intType" />
				<element name="uint9" type="tns:intType" />
				<element name="uint12" type="tns:intType" />
				<element name="uint13" type="tns:intType" />
				<element name="uint14" type="tns:intType" />
				<element name="uint15" type="tns:intType" />
				<element name="uint16" type="tns:intType" />
				<element name="uint20" type="tns:intType" />
				<element name="uint30" type="tns:intType" />
				<element name="uint32" type="tns:intType" />
				<element name="type" type="tns:typeType" />
				<element name="choice" type="tns:choiceType" />
				<element name="text" type="string" />
				<element name="hex" type="hexBinary" />
			</choice>
			<element name="limitation" type="tns:limitationType"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="NCName" use="required" />
	</complexType>
	<complexType name="msoType">
		<sequence>
			<element name="const" minOccurs="0" maxOccurs="unbounded" />
			<element name="struct" type="tns:structType" minOccurs="0"
				maxOccurs="unbounded">
				<unique name="uniqueMembers">
					<selector xpath="*" />
					<field xpath="@name" />
				</unique>
			</element>
			<element name="stream" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<element name="mso" type="tns:msoType">
		<key name="uniqueStructs">
			<selector xpath="tns:struct" />
			<field xpath="@name" />
		</key>
		<keyref name="structRef" refer="tns:uniqueStructs">
			<selector xpath="tns:struct/tns:type" />
			<field xpath="@type" />
		</keyref>
		<keyref name="structRef2" refer="tns:uniqueStructs">
			<selector xpath="tns:struct/tns:choice/tns:type" />
			<field xpath="@type" />
		</keyref>
	</element>
</schema>

=== KDE/binschema/src/pdf.xml
<!-- This document is a loose version of a way to describe parts of a PDF -->
<mso xmlns="http://www.example.org/mso" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/mso mso.xsd">
	<struct name="PDF">
		<type name="header" type="Header" />
		<type name="body" type="Body" />
		<type name="crossReferenceTable" type="CrossReferenceTable" />
		<type name="trailer" type="Trailer" />
	</struct>
	<struct name="Whitespace">
		<uint8 name="ws">
			<limitation value="0x00|0x09|0x0A|0x0C|0x0D|0x20" />
		</uint8>
	</struct>
	<struct name="Delimiter">
		<uint8 name="delimiter">
			<limitation value="'('|')'|'['|']'|'{'|'}'|'/'|'%'" />
		</uint8>
	</struct>
	<struct name="Digit">
		<uint8 name="digit">
			<limitation value="'0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'" />
		</uint8>
	</struct>
	<struct name="Eol">
		<hex>0D0A</hex>
	</struct>
	<struct name="Header">
		<text>%PDF-1.3</text>
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
	</struct>
	<struct name="Body">
	</struct>
	<struct name="CrossReferenceLine">
		<type name="offset" count="10" type="Digit" />
		<hex>20</hex>
		<type name="generation" count="5" type="Digit" />
		<hex>20</hex>
		<uint8 name="state">
			<limitation value="'n'|'f'" />
		</uint8>
		<hex>0D0A</hex>
	</struct>
	<struct name="CrossReferenceSection">
		<type name="start" array="true" type="Digit" />
		<hex>20</hex>
		<type name="offset" array="true" type="Digit" />
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<type name="entries" type="CrossReferenceLine" minCount="1"
			maxCount="unbounded" />
	</struct>
	<struct name="CrossReferenceTable">
		<text>xref</text>
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<type name="sections" type="CrossReferenceSection" minCount="1"
			maxCount="unbounded" />
	</struct>
	<struct name="Boolean">
		<choice name="boolean">
			<text>true</text>
			<text>false</text>
		</choice>
	</struct>
	<struct name="Integer">
		<uint8 name="sign">
			<limitation value="'+'|'-'" />
		</uint8>
		<type name="value" minCount="1" maxCount="unbounded" type="Digit" />
	</struct>
	<struct name="Real">
		<uint8 name="sign">
			<limitation value="'+'|'-'" />
		</uint8>
		<type name="integer" minCount="0" maxCount="unbounded" type="Digit" />
		<text>.</text>
		<type name="fraction" minCount="0" maxCount="unbounded" type="Digit" />
	</struct>
	<struct name="Number">
		<choice name="value">
			<type type="Integer" />
			<type type="Real" />
		</choice>
	</struct>
	<struct name="EscapedCharacter">
		<text>\</text>
		<uint8 name="character" />
	</struct>
	<struct name="ParenthesisStringCharacters">
		<uint8 name="literal" minCount="1" maxCount="unbounded">
			<limitation expression="!='\'" />
			<limitation expression="!=')'" />
			<limitation expression="!='('" />
		</uint8>
	</struct>
	<struct name="ParenthesisStringContent">
		<choice name="content">
			<type type="EscapedCharacter" />
			<type type="ParenthesisStringCharacters" />
			<type type="ParenthesisString" />
		</choice>
	</struct>
	<struct name="ParenthesisString">
		<text>(</text>
		<type name="string" type="ParenthesisStringContent" array="true" />
		<text>)</text>
	</struct>
	<struct name="Hexadecimal">
		<uint8 name="character">
			<limitation
				value="'0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'|'a'|'b'|'c'|'d'|'e'|'f'|'A'|'B'|'C'|'D'|'E'|'F'" />
		</uint8>
	</struct>
	<struct name="HexadecimalStringContent">
		<type type="Hexadecimal" name="a" />
		<type name="ws" type="Whitespace" array="true" />
		<type type="Hexadecimal" name="b" />
		<type name="ws2" type="Whitespace" array="true" />
	</struct>
	<struct name="HexadecimalString">
		<text>&lt;</text>
		<type name="string" type="HexadecimalStringContent" array="true" />
		<text>&gt;</text>
	</struct>
	<struct name="String">
		<choice name="string">
			<type type="ParenthesisString" />
			<type type="HexadecimalString" />
		</choice>
	</struct>
	<struct name="Name">
		<text>/</text>
		<uint8 name="name" array="true">
			<limitation expression="!=0x00" />
			<limitation expression="!=0x09" />
			<limitation expression="!=0x0A" />
			<limitation expression="!=0x0C" />
			<limitation expression="!=0x0D" />
			<limitation expression="!=0x20" />
			<limitation expression="!='('" />
			<limitation expression="!=')'" />
			<limitation expression="!='['" />
			<limitation expression="!=']'" />
			<limitation expression="!='{'" />
			<limitation expression="!='}'" />
			<limitation expression="!='/'" />
			<limitation expression="!='%'" />
		</uint8>
	</struct>
	<struct name="ArrayEntry">
		<choice name="entry">
			<type type="Number" />
			<type type="String" />
			<type type="Dictionary" />
			<type type="Array" />
		</choice>
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
	</struct>
	<struct name="Array">
		<text>[</text>
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<type name="entries" type="ArrayEntry" array="true" />
		<text>]</text>
	</struct>
	<struct name="Object">
		<choice name="entry">
			<type type="Number" />
			<type type="String" />
			<type type="Dictionary" />
			<type type="Array" />
		</choice>
	</struct>
	<struct name="DictionaryEntry">
		<type name="key" type="Name" />
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<type name="value" type="Object" />
		<type name="ws2" type="Whitespace" minCount="1" maxCount="unbounded" />
	</struct>
	<struct name="Dictionary">
		<text>&lt;&lt;</text>
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<type name="entries" type="DictionaryEntry" array="true" />
		<text>&gt;&gt;</text>
	</struct>
	<struct name="Stream">
		<type name="info" type="Dictionary" />
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<text>stream</text>
		<choice name="ws2">
			<hex>0A</hex>
			<hex>0D0A</hex>
		</choice>
		<uint8 name="stream" count="info['Length']" />
		<choice name="endstream">
			<hex>0A6E65736472746165</hex>
			<hex>0D6E65736472746165</hex>
			<hex>0D0A6E65736472746165</hex>
			<text>endstream</text>
		</choice>
	</struct>
	<struct name="Null">
		<text>null</text>
	</struct>
	<struct name="Trailer">
		<text>trailer</text>
		<text>startxref</text>
		<type name="ws" type="Whitespace" minCount="1" maxCount="unbounded" />
		<type name="startxref" array="true" type="Digit" />
		<text>%%EOF</text>
	</struct>
</mso>

=== KDE/binschema/src/mso.xml
<?xml version="1.0" encoding="UTF-8"?>
<mso xmlns='http://www.example.org/mso' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:schemaLocation='http://www.example.org/mso mso.xsd'>
	<const name="RT_CurrentUserAtom" value="0x0FF6" />
	<struct name="RecordHeader">
		<uint4 name="recVer" />
		<uint12 name="recInstance" />
		<uint16 name="recType" />
		<uint32 name="recLen" />
	</struct>
	<struct name="CurrentUserAtom">
		<type name="rh" type="RecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0" />
			<limitation name="recType" value="0x0FF6" />
			<!--
				valueRef="RT_CurrentUserAtom" />
			-->
		</type>
		<uint32 name="size">
			<limitation value="0x14" />
		</uint32>
		<uint32 name="headerToken">
			<limitation value="0xE391C05F|0xF3D1C4DF" />
		</uint32>
		<uint32 name="offsetToCurrentEdit" />
		<uint16 name="lenUserName">
			<limitation expression="&lt;=255" />
		</uint16>
		<uint16 name="docFileVersion">
			<limitation value="0x03F4" />
		</uint16>
		<uint8 name="majorVersion">
			<limitation value="0x03" />
		</uint8>
		<uint8 name="minorVersion">
			<limitation value="0x00" />
		</uint8>
		<uint16 name="unused" />
		<uint8 name="ansiUserName" count="lenUserName" />
		<uint32 name="relVersion">
			<limitation value="0x8|0x9" />
		</uint32>
		<uint8 name="unicodeUserName" count="2*lenUserName" condition="rh.recLen==3*lenUserName" />
	</struct>
	<struct name="CurrentUserStream">
		<type name="anon1" type="CurrentUserAtom" />
	</struct>
	<struct name="PicturesStream">
		<type name="anon1" type="OfficeArtBStoreDelay" />
	</struct>
	<struct name="OfficeArtBStoreDelay">
		<type name="anon1" array="true" type="OfficeArtBStoreContainerFileBlock" />
	</struct>
	<struct name="OfficeArtRecordHeader">
		<uint4 name="recVer" />
		<uint12 name="recInstance" />
		<uint16 name="recType" />
		<uint32 name="recLen" />
	</struct>
	<struct name="OfficeArtFBSE">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0x2" />
			<limitation name="recInstance"
				value="0xF01A|0xF01B|0xF01C|0xF01D|0xF01E|0xF01F|0xF029" />
			<limitation name="recType" value="0xF007" />
		</type>
		<uint8 name="btWin32" />
		<uint8 name="btMacOS" />
		<uint8 name="rgbUid" array="true" count="16" />
		<uint16 name="tag" />
		<uint32 name="size">
			<limitation expression="&gt;=8" />
		</uint32>
		<uint32 name="cRef" />
		<uint32 name="foDelay" />
		<uint8 name="unused1" />
		<uint8 name="cbName" />
		<uint8 name="unused2" />
		<uint8 name="unused3" />
		<uint8 name="nameData" array="true" count="rh.recLen-size-36" />
		<type name="embeddedBlip" type="OfficeArtBlip" condition="size > 0">
			<!--
				this limitation is currently not supported because it requires
				dynamic introspection <limitation name="rh.recInstance"
				value="rh.recInstance" />
			-->
		</type>
	</struct>
	<struct name="OfficeArtBlipEMF">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x3D4|0x3D5" />
			<limitation name="recType" value="0xF01A" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x3D5" />
		<type name="metafileHeader" type="OfficeArtMetafileHeader" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance==0x3D4)?50:66)" />
	</struct>
	<struct name="OfficeArtBlipWMF">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x216|0x217" />
			<limitation name="recType" value="0xF01B" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x217" />
		<type name="metafileHeader" type="OfficeArtMetafileHeader" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance==0x216)?50:66)" />
	</struct>
	<struct name="OfficeArtBlipPICT">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x542|0x543" />
			<limitation name="recType" value="0xF01C" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x543" />
		<type name="metafileHeader" type="OfficeArtMetafileHeader" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance==0x542)?50:66)" />
	</struct>
	<struct name="OfficeArtBlipJPEG">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x46A|0x46B|0x6E2|0x6E3" />
			<limitation name="recType" value="0xF01D" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x46B || rh.recInstance == 0x6E3" />
		<uint8 name="tag" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance == 0x46A || rh.recInstance == 0x6E2)?17:33)" />
	</struct>
	<struct name="OfficeArtBlipPNG">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x6E0|0x6E1" />
			<limitation name="recType" value="0xF01E" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x6E1" />
		<uint8 name="tag" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance==0x6E0)?17:33)" />
	</struct>
	<struct name="OfficeArtBlipDIB">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x7A8|0x7A9" />
			<limitation name="recType" value="0xF01F" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x7A9" />
		<uint8 name="tag" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance==0x7A8)?17:33)" />
	</struct>
	<struct name="OfficeArtBlipTIFF">
		<type name="rh" type="OfficeArtRecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x6E4|0x6E5" />
			<limitation name="recType" value="0xF020" />
		</type>
		<uint8 name="rgbUid1" array="true" count="16" />
		<uint8 name="rgbUid2" array="true" count="16"
			condition="rh.recInstance == 0x6E5" />
		<uint8 name="tag" />
		<uint8 name="BLIPFileData" array="true"
			count="rh.recLen-((rh.recInstance==0x6E4)?17:33)" />
	</struct>
	<struct name="OfficeArtMetafileHeader">
		<uint32 name="cbSize" />
		<type name="rcBounds" type="RECT" />
		<type name="ptSize" type="POINT" />
		<uint32 name="cbsave" />
		<uint8 name="compression" />
		<uint8 name="filter" />
	</struct>
	<struct name="RECT">
		<int32 name="left" />
		<int32 name="top" />
		<int32 name="right" />
		<int32 name="bottom" />
	</struct>
	<struct name="POINT">
		<int32 name="x" />
		<int32 name="y" />
	</struct>
	<struct name="OfficeArtBlip">
		<choice name="anon">
			<type type="OfficeArtBlipEMF" />
			<type type="OfficeArtBlipWMF" />
			<type type="OfficeArtBlipPICT" />
			<type type="OfficeArtBlipJPEG" />
			<type type="OfficeArtBlipPNG" />
			<type type="OfficeArtBlipDIB" />
			<type type="OfficeArtBlipTIFF" />
		</choice>
	</struct>
	<struct name="OfficeArtBStoreContainerFileBlock">
		<choice name="anon">
			<type type="OfficeArtFBSE" />
			<type type="OfficeArtBlip" />
		</choice>
	</struct>
	<struct name="PowerPointStructs">
		<type name="anon" type="PowerPointStruct" array="true" />
	</struct>
	<struct name="PowerPointStruct">
		<choice name="anon">
			<type type="DocumentContainer" />
			<type type="MasterOrSlideContainer" />
		</choice>
	</struct>
	<struct name="DocumentContainer">
		<type name="rh" type="RecordHeader">
			<limitation name="recVer" value="0xF" />
			<limitation name="recInstance" value="0x0" />
			<limitation name="recType" value="0x03E8" />
		</type>
		<type name="documentAtom" type="DocumentAtom" />
	</struct>
	<struct name="DocumentAtom">
		<type name="rh" type="RecordHeader">
			<limitation name="recVer" value="1" />
			<limitation name="recInstance" value="0x0" />
			<limitation name="recType" value="0x03E9" />
			<limitation name="recLen" value="0x28" />
		</type>
		<type name="slideSize" type="PointStruct" />
		<type name="notesSize" type="PointStruct" />
		<type name="serverZoom" type="RatioStruct">
			<limitation expression="numer*denom &gt; 0" />
		</type>
	</struct>
	<struct name="PointStruct">
		<int32 name="x" />
		<int32 name="y" />
	</struct>
	<struct name="RatioStruct">
		<int32 name="numer" />
		<int32 name="denom">
			<limitation expression="!= 0" />
		</int32>
	</struct>
	<struct name="MasterOrSlideContainer">
		<type name="rh" type="RecordHeader">
			<limitation name="recVer" value="0" />
			<limitation name="recInstance" value="0x0" />
			<limitation name="recType" value="0x03EE|0x03F8" />
		</type>
	</struct>
	<stream name="PowerPointDocument" key="PowerPoint Document"
		type="DocumentContainer" /> <!-- should be PowerPointStructs -->
	<stream name="CurrentUser" key="Current User" type="CurrentUserAtom" />
	<!--
		<stream name="Pictures" key="Pictures" type="OfficeArtBStoreDelay" />
	-->
</mso>
